version: "3.9"

services:
    db:
        image: postgres 
        environment:
            - POSTGRES_DB=FirePay
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=admin@FirePay_123

    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/src
        ports:
            - "8000:8000"
        depends_on:
            - db 